apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.ingressName }}-ingress 
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      {{- range $k, $v := .Values.rules }}
      - path: {{ $v.path }}
        pathType: Prefix
        backend: 
          service:
            name: {{ $v.service }}
            port:
              number: {{ $v.port }}
      {{- end }}
